In [ ]:
import polars as pl
from getpass import getpass
from sqlalchemy import create_engine, URL

from tqdm import tqdm

In [ ]:
username = input("Username:")
password = getpass("Password:")

In [ ]:
iedb_url = URL.create(
    "mysql+mysqlconnector",
    username=username,
    password=password,  # plain (unescaped) text
    host="81.177.141.179",
    port = 3306,
    database="IEDB"
)
cedar_url = URL.create(
    "mysql+mysqlconnector",
    username=username,
    password=password,  # plain (unescaped) text
    host="81.177.141.179",
    port = 3306,
    database="CEDAR"
)

In [ ]:
iedb_uri = f"mysql://{username}:{password}@81.177.141.179:3306/IEDB"
cedar_uri = f"mysql://{username}:{password}@81.177.141.179:3306/CEDAR"
tables["organism_names"] = pl.read_database_uri(query = "SELECT organism_id, name_txt FROM organism_names WHERE name_class = 'scientific name';", uri = iedb_uri)
tables["organism_names"].head()

In [ ]:
table_names = ["tcell","curated_epitope","object","epitope_object","epitope", "tcell_receptor","curated_receptor","distinct_receptor","distinct_chain","mhc_allele_restriction"]
tables = {}
conn = create_engine(iedb_url)
batch_size = 100000
for name in tqdm(table_names):
    tbl = pl.DataFrame()
    for chunk in tqdm(pl.read_database(query = f"SELECT * FROM {name};", connection=conn.connect(), batch_size = batch_size, iter_batches=True,infer_schema_length=10000)):
        tbl = pd.concat([tbl, chunk])
    tables[name] = tbl

In [ ]:
tcell_iter = pl.read_database(query = f"SELECT * FROM {name};", connection=conn.connect(), batch_size = batch_size, iter_batches=True,infer_schema_length=10000)

In [ ]:
%%time
from mysql.connector import connect, Error as MysqlError
import pandas as pd
chunk_size = 100000
conn = create_engine(iedb_url)
tbl = pd.DataFrame()
for chunk in tqdm(pd.read_sql(f"SELECT * FROM tcell;", con = conn.connect(), chunksize = chunk_size)):
    tbl = pd.concat([tbl, chunk], ignore_index = False)
tbl.head()

In [19]:
import os
import time
import uuid
import warnings
import mhcgnomes
import traceback
import numpy as np
import pandas as pd


def fix_mhc_name(allele_str, chain = 'alpha'):
    try:
        # Предварительные проверки и подготовления
        if pd.isna(allele_str):
            return pd.NA     
        allele_first = allele_str.split(" ")[0]
        if allele_first == "B2M":
            return "B2M"
        # Получение конкретной аллели
        parsed_allele = mhcgnomes.parse(allele_first)
        if isinstance(parsed_allele, mhcgnomes.pair.Pair):
            if chain == 'alpha':
                allele = parsed_allele.alpha
            elif chain == 'beta':
                allele = parsed_allele.beta
            else:
                raise ValueError('Unknown chain')
        elif isinstance(parsed_allele, mhcgnomes.allele.Allele):
            allele = parsed_allele
        else:
            raise ValueError('Not allele')
        # Проверка
        if allele.gene.species.name == "Homo sapiens":
            if len(allele.allele_fields) < 2:
                raise ValueError('Too many allele fields. Need at least 2.')
            elif len(allele.allele_fields) == 2:
                return allele.to_string()
            else:
                return allele.restrict_allele_fields(2, drop_annotations=True, drop_mutations=True).to_string()
        elif allele.gene.species.name == "Mus musculus":
            return allele.to_string()
        else:
            raise ValueError('Wrong species. Only human and mouse are allowed.')
    except (mhcgnomes.errors.ParseError, TypeError, ValueError):
        return pd.NA

def calculate_receptor_id(data: pd.DataFrame, column: str) -> pd.DataFrame:
    cleaned_data = data.copy(deep=True)
    unique_id = cleaned_data[column].unique()
    replacement = {k:str(uuid.uuid4()) for k in unique_id}
    cleaned_data[column] = cleaned_data[column].map(replacement)
    return cleaned_data

PROTEIN_CHECK="^[ACDEFGHIKLMNPQRSTVWY]+$"
HOST_SPECIES = ['human', 'mouse']
CDR3_CHAINS = ['alpha', 'beta']

In [25]:
raw_data = pd.read_csv("../../data/raw-data/IEDB/IEDB.csv", sep = ";", header = 0)
print(raw_data.shape)
species_columns_to_clean = ["species_name_receptor","species_name_chain","mhc_source","host_organism"]
print("Unificate species")
for col in species_columns_to_clean:
    raw_data.loc[raw_data[col].str.contains("Homo sapiens"),col] = "human"
    raw_data.loc[raw_data[col].str.contains("Mus musculus"),col] = "mouse"
print("Check mhc names")

raw_data.loc[raw_data['chain_ii_name'].str.contains("Beta-2-microglobulin"),'chain_ii_name'] = "B2M"
raw_data['valid_i_name'] = raw_data['chain_i_name'].apply(lambda x: fix_mhc_name(x, 'alpha'))
raw_data['valid_ii_name'] = raw_data['chain_ii_name'].apply(lambda x: fix_mhc_name(x, 'beta'))

table_schema = {
        "id": "id",
        "chain_type": "chain",
        "cdr3_seq": "sequence",
        "linear_peptide_seq": "epitope",
        "valid_i_name": "mhc_alpha",
        "valid_ii_name": "mhc_beta",
        "class": "mhc_class",
        "host_organism": "host_species",
        "epitope_source": "epitope_species",
        "source_antigen_accession": "epitope_source",
        "v_gene": "V",
        "d_gene": "D",
        "j_gene": "J",
        "database": "database"
    }


print("Apply filters")
clean_data = raw_data.\
        query("reference_id.notna()").\
        query("receptor_type_x == 'alphabeta'").\
        query("chain_type.isin(@CDR3_CHAINS)").\
        query("species_name_receptor == species_name_chain == host_organism == mhc_source and species_name_receptor.isin(@HOST_SPECIES)").\
        query("cdr3_seq.notna()").\
        query("cdr3_seq.str.contains(@PROTEIN_CHECK)").\
        query("e_region_domain_flag == 'Exact Epitope'").\
        query("linear_peptide_seq.notna()").\
        query("linear_peptide_seq.str.contains(@PROTEIN_CHECK)").\
        query("linear_peptide_modification.isna()").\
        query("disc_region.isna()").\
        query("ant_type == 'Epitope'").\
        query("valid_i_name.notna() and valid_ii_name.notna()").\
        query("as_char_value.str.contains('Positive')")        
#clean_data = raw_data.copy(deep=True)        
print(clean_data.shape)
   
print("Get id")
unique_id = clean_data["curated_receptor_id"].unique()
replacement = {k:str(uuid.uuid4()) for k in unique_id}
clean_data["id"] = clean_data["curated_receptor_id"].map(replacement)
clean_data["database"] = "IEDB"
clean_data_selected = clean_data.filter(items = list(table_schema.keys()), axis = 1).rename(columns = table_schema)
    
print("Reshape")
pivoted_part = clean_data_selected.filter(["id", "chain", "sequence","V","D","J"],axis=1).sort_values(by='V', na_position='last')
annotation_part = clean_data_selected.filter(["id", "epitope", "mhc_alpha","mhc_beta","mhc_class","host_species","epitope_species","epitope_source","database"],axis=1)
pivoted_part_pivot = pivoted_part.pivot_table(index = "id",columns='chain', values=['sequence', 'V', 'D', 'J'], aggfunc = 'first').reset_index()
pivoted_part_pivot.head()

/tmp/ipykernel_8648/2019829177.py:1: DtypeWarning: Columns (0: as_location, 1: as_inequality, 2: as_immunization_comments, 3: as_comments, 4: h_gaz_id, 5: h_sex, 6: h_age, 7: h_mhc_types_present, 8: tcr_name, 9: tcr_c1_mol_type, 10: tcr_c2_mol_type, 11: iv1_adjuvants, 12: iv1_route, 13: iv1_dose_schedule, 14: iv1_disease_stage, 15: iv1_imm_type, 16: iv1_imm_ref_name, 17: iv1_imm_ev, 18: iv2_process_type, 19: iv2_adjuvants, 20: iv2_route, 21: iv2_dose_schedule, 22: iv2_disease_stage, 23: iv2_imm_type, 24: iv2_imm_ref_name, 25: iv2_imm_ev, 26: ivt_process_type, 27: ivt_responder_cell_type, 28: ivt_stimulator_cell_type, 29: ivt_imm_type, 30: ivt_imm_ref_name, 31: ivt_imm_ev, 32: adt_iv_process_type, 33: adt_iv_adjuvants, 34: adt_iv_route, 35: adt_iv_dose_schedule, 36: adt_iv_disease_stage, 37: adt_iv_imm_type, 38: adt_iv_imm_ref_name, 39: adt_iv_imm_ev, 40: adt_tcr_name, 41: adt_tcr_c1_mol_type, 42: adt_tcr_c2_mol_type, 43: adt_h_gaz_id, 44: adt_h_age, 45: adt_h_sex, 46: adt_h_mhc_types_present, 47: adt_effector_cell_type, 48: adt_effector_tissue_type, 49: adt_effector_origin, 50: adt_comments, 51: mhc_autologous, 52: apc_cell_type, 53: apc_tissue_type, 54: apc_origin, 55: apc_h_age, 56: apc_h_sex, 57: apc_h_mhc_types_present, 58: ant_ref_name, 59: synonyms, 60: includes, 61: haplotype, 62: locus, 63: molecule, 64: chain_i_name, 65: chain_ii_name, 66: chain_i_mutation, 67: chain_i_accession, 68: chain_ii_accession, 69: chain_i_mro_id, 70: chain_ii_mro_id, 71: v_dom_seq, 72: v_gene, 73: d_gene, 74: j_gene, 75: cdr1_seq, 76: cdr2_seq, 77: ref_name, 78: ref_synonyms, 79: chain1_nt_acc, 80: chain1_nt_seq, 81: chain1_pro_acc, 82: chain1_pro_seq, 83: chain2_nt_acc, 84: chain2_nt_seq, 85: chain2_pro_acc, 86: chain2_pro_seq, 87: region, 88: mol1_modified_seq, 89: mol1_modification, 90: linear_peptide_modified_seq, 91: linear_peptide_modification, 92: disc_region, 93: e_location, 94: e_comments, 95: e_ev, 96: e_ref_region) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv("../../data/raw-data/IEDB/IEDB.csv", sep = ";", header = 0)

(273436, 214)
Unificate species
Check mhc names
Apply filters
(161862, 216)
Get id
Reshape

                                         id     D                    J  \
chain                                       alpha      beta      alpha
0      00000075-645e-4659-a53f-a5aa33dd9c32   NaN       NaN     TRAJ57
1      0000f96d-cad3-4d7f-b140-b2bfb2fcfa88   NaN       NaN  TRAJ58*01
2      0002216a-84d1-4c47-9f91-a259c0d3f343   NaN  TRBD2*02        NaN
3      0002cda8-67ef-41f0-8a2a-fd720e944554   NaN       NaN        NaN
4      0002f86f-798f-4a35-bcd8-16fbe952ffb6   NaN  TRBD1*01        NaN

                               V                 sequence
chain        beta          alpha      beta          alpha             beta
0         TRBJ2-3       TRAV13-2     TRBV2  AELRFQGGSEKLV        ASGGSDTQY
1             NaN  TRAV36/DV7*01       NaN   AVSQETSGSRLT              NaN
2      TRBJ2-1*01            NaN     TRBV3            NaN     ASTSSGSVYEQF
3         TRBJ2-2            NaN  TRBV12-3            NaN  ASRGTSGGPNTGELF
4      TRBJ2-1*01            NaN    TRBV20            NaN     SAPEGASYNEQF

In [26]:
pivoted_part_pivot1 = pivoted_part_pivot.copy(deep=True)
pivoted_part_pivot1.columns = pivoted_part_pivot1.columns.to_flat_index().str.join('_')
pivoted_part_pivot1.rename(columns = {"id_":"id", "sequence_alpha":"cdr3_alpha", "sequence_beta":'cdr3_beta'},inplace=True)
wide = pd.merge(pivoted_part_pivot1, annotation_part, on="id")
print(wide.shape)
wide.head()

(161862, 17)

,id,D_alpha,D_beta,J_alpha,J_beta,V_alpha,V_beta,cdr3_alpha,cdr3_beta,epitope,mhc_alpha,mhc_beta,mhc_class,host_species,epitope_species,epitope_source,database
0,00000075-645e-4659-a53f-a5aa33dd9c32,NaN,NaN,TRAJ57,TRBJ2-3,TRAV13-2,TRBV2,AELRFQGGSEKLV,ASGGSDTQY,RVRAYTYSK,HLA-A*03:01,B2M,I,human,human gammaherpesvirus 4,Q3KSS7.1,IEDB
1,00000075-645e-4659-a53f-a5aa33dd9c32,NaN,NaN,TRAJ57,TRBJ2-3,TRAV13-2,TRBV2,AELRFQGGSEKLV,ASGGSDTQY,RVRAYTYSK,HLA-A*03:01,B2M,I,human,human gammaherpesvirus 4,Q3KSS7.1,IEDB
2,0000f96d-cad3-4d7f-b140-b2bfb2fcfa88,NaN,NaN,TRAJ58*01,NaN,TRAV36/DV7*01,NaN,AVSQETSGSRLT,NaN,YVLDHLIVV,HLA-A*02:01,B2M,I,human,human gammaherpesvirus 4,ABB89247.1,IEDB
3,0002216a-84d1-4c47-9f91-a259c0d3f343,NaN,TRBD2*02,NaN,TRBJ2-1*01,NaN,TRBV3,NaN,ASTSSGSVYEQF,GLCTLVAML,HLA-A*02:01,B2M,I,human,human gammaherpesvirus 4,YP_401660.1,IEDB
4,0002cda8-67ef-41f0-8a2a-fd720e944554,NaN,NaN,NaN,TRBJ2-2,NaN,TRBV12-3,NaN,ASRGTSGGPNTGELF,NLVPMVATV,HLA-A*02:01,B2M,I,human,Human betaherpesvirus 5,P06725.2,IEDB

In [27]:
len(wide['epitope'].unique())

1375

1375

In [67]:
if isinstance(a,mhcgnomes.allele.Allele):
    print("meow")

meow

In [58]:
a.gene.species.name == 'Homo sapiens'

True

In [55]:
pd.set_option("display.max_columns",500)
raw_data[['chain_i_name', 'chain_ii_name','valid_i_name','valid_ii_name']].head(5)

  chain_i_name chain_ii_name valid_i_name valid_ii_name
0  HLA-A*02:01           B2M         <NA>           B2M
1  HLA-A*02:01           B2M         <NA>           B2M
2  HLA-A*02:01           B2M         <NA>           B2M
3  HLA-A*02:01           B2M         <NA>           B2M
4  HLA-B*51:01           B2M         <NA>           B2M

In [ ]:
raw_data['valid_i_name'].value_counts(dropna=False)

In [ ]:
raw_data['valid_ii_name'].value_counts(dropna=False)

In [ ]:
raw_data['class'].value_counts(dropna=False)

In [23]:
pivoted_part_pivot1 = pivoted_part_pivot.copy(deep=True)
pivoted_part_pivot1.columns = pivoted_part_pivot1.columns.to_flat_index().str.join('_')
pivoted_part_pivot1.rename(columns = {"id_":"id", "sequence_alpha":"cdr3_alpha", "sequence_beta":'cdr3_beta'},inplace=True)
pivoted_part_pivot1.head()

,id,D_alpha,D_beta,D_delta,J_alpha,J_beta,J_delta,J_gamma,V_alpha,V_beta,V_construct,V_delta,V_gamma,cdr3_alpha,cdr3_beta,sequence_construct,sequence_delta,sequence_gamma
0,00005fb6-c4f5-48b6-8df9-357a87aba84e,NaN,TRBD1*01,NaN,NaN,TRBJ2-5*01,NaN,NaN,NaN,TRBV29-1*01,NaN,NaN,NaN,NaN,SVEEDRVRQSQY,NaN,NaN,NaN
1,00006e5b-1553-41e0-94ac-c4341d3ae5ba,NaN,NaN,NaN,TRAJ37,NaN,NaN,NaN,TRAV12-2,NaN,NaN,NaN,NaN,AVTSNTGKLI,NaN,NaN,NaN,NaN
2,0000d549-d190-4c3d-9a9e-81b0c2a8a2e7,NaN,NaN,NaN,NaN,TRBJ2-1,NaN,NaN,NaN,TRBV28,NaN,NaN,NaN,NaN,ASSTRGAPQF,NaN,NaN,NaN
3,000130ba-1908-4969-818d-e347e8e0eaaa,NaN,NaN,NaN,NaN,TRBJ2-6,NaN,NaN,NaN,TRBV6-5,NaN,NaN,NaN,NaN,ASSSTAGANVLT,NaN,NaN,NaN
4,0001bc9c-1c74-4848-a4ad-0ebbf79d49da,NaN,NaN,NaN,NaN,TRBJ2-5,NaN,NaN,NaN,TRBV12,NaN,NaN,NaN,NaN,ASSSPGTAQETQY,NaN,NaN,NaN

In [ ]:
pivoted_part_pivot1.shape

In [24]:
wide = pd.merge(pivoted_part_pivot1, annotation_part, on="id")
print(wide.shape)
wide.head()

(273430, 26)

,id,D_alpha,D_beta,D_delta,J_alpha,J_beta,J_delta,J_gamma,V_alpha,V_beta,...,sequence_delta,sequence_gamma,epitope,mhc_alpha,mhc_beta,mhc_class,host_species,epitope_species,epitope_source,database
0,00005fb6-c4f5-48b6-8df9-357a87aba84e,NaN,TRBD1*01,NaN,NaN,TRBJ2-5*01,NaN,NaN,NaN,TRBV29-1*01,...,NaN,NaN,GLCTLVAML,HLA-A*02:01,B2M,I,human,human gammaherpesvirus 4,YP_401660.1,IEDB
1,00006e5b-1553-41e0-94ac-c4341d3ae5ba,NaN,NaN,NaN,TRAJ37,NaN,NaN,NaN,TRAV12-2,NaN,...,NaN,NaN,VMATRRNVL,HLA-E*01:03,B2M,non classical,human,Mycobacterium tuberculosis,COW42455.1,IEDB
2,0000d549-d190-4c3d-9a9e-81b0c2a8a2e7,NaN,NaN,NaN,NaN,TRBJ2-1,NaN,NaN,NaN,TRBV28,...,NaN,NaN,FLWLLWPVTLACFVLAAV,NaN,NaN,I,human,Severe acute respiratory syndrome coronavirus 2,YP_009724393.1,IEDB
3,000130ba-1908-4969-818d-e347e8e0eaaa,NaN,NaN,NaN,NaN,TRBJ2-6,NaN,NaN,NaN,TRBV6-5,...,NaN,NaN,FLWLLWPVTLACFVLAAV,NaN,NaN,I,human,Severe acute respiratory syndrome coronavirus 2,YP_009724393.1,IEDB
4,0001bc9c-1c74-4848-a4ad-0ebbf79d49da,NaN,NaN,NaN,NaN,TRBJ2-5,NaN,NaN,NaN,TRBV12,...,NaN,NaN,VLPFNDGVYFASTEK,NaN,NaN,I,human,Severe acute respiratory syndrome coronavirus 2,YP_009724390.1,IEDB

In [7]:

raw_data = pd.read_csv("../../data/raw-data/IEDB/IEDB.csv", sep = ";", header = 0)
print(raw_data.shape)
species_columns_to_clean = ["species_name_receptor","species_name_chain","mhc_source","host_organism"]
print("Unificate species")
for col in species_columns_to_clean:
    raw_data.loc[raw_data[col].str.contains("Homo sapiens"),col] = "human"
    raw_data.loc[raw_data[col].str.contains("Mus musculus"),col] = "mouse"
print("Check mhc names")
raw_data.loc[raw_data['chain_ii_name'].str.contains("Beta-2-microglobulin"),'chain_ii_name'] = "B2M"
from tqdm import tqdm
invalid_mhci = set()
for mhci in tqdm(raw_data['chain_i_name']):
    if pd.isna(fix_mhc_name(mhci)):
        invalid_mhci.add(mhci)

invalid_mhcii = set()
for mhcii in tqdm(raw_data['chain_ii_name']):
    if pd.isna(fix_mhc_name(mhcii)):
        invalid_mhcii.add(mhcii)

print(invalid_mhci)
print(invalid_mhcii)

/tmp/ipykernel_8648/2750529512.py:1: DtypeWarning: Columns (0: as_location, 1: as_inequality, 2: as_immunization_comments, 3: as_comments, 4: h_gaz_id, 5: h_sex, 6: h_age, 7: h_mhc_types_present, 8: tcr_name, 9: tcr_c1_mol_type, 10: tcr_c2_mol_type, 11: iv1_adjuvants, 12: iv1_route, 13: iv1_dose_schedule, 14: iv1_disease_stage, 15: iv1_imm_type, 16: iv1_imm_ref_name, 17: iv1_imm_ev, 18: iv2_process_type, 19: iv2_adjuvants, 20: iv2_route, 21: iv2_dose_schedule, 22: iv2_disease_stage, 23: iv2_imm_type, 24: iv2_imm_ref_name, 25: iv2_imm_ev, 26: ivt_process_type, 27: ivt_responder_cell_type, 28: ivt_stimulator_cell_type, 29: ivt_imm_type, 30: ivt_imm_ref_name, 31: ivt_imm_ev, 32: adt_iv_process_type, 33: adt_iv_adjuvants, 34: adt_iv_route, 35: adt_iv_dose_schedule, 36: adt_iv_disease_stage, 37: adt_iv_imm_type, 38: adt_iv_imm_ref_name, 39: adt_iv_imm_ev, 40: adt_tcr_name, 41: adt_tcr_c1_mol_type, 42: adt_tcr_c2_mol_type, 43: adt_h_gaz_id, 44: adt_h_age, 45: adt_h_sex, 46: adt_h_mhc_types_present, 47: adt_effector_cell_type, 48: adt_effector_tissue_type, 49: adt_effector_origin, 50: adt_comments, 51: mhc_autologous, 52: apc_cell_type, 53: apc_tissue_type, 54: apc_origin, 55: apc_h_age, 56: apc_h_sex, 57: apc_h_mhc_types_present, 58: ant_ref_name, 59: synonyms, 60: includes, 61: haplotype, 62: locus, 63: molecule, 64: chain_i_name, 65: chain_ii_name, 66: chain_i_mutation, 67: chain_i_accession, 68: chain_ii_accession, 69: chain_i_mro_id, 70: chain_ii_mro_id, 71: v_dom_seq, 72: v_gene, 73: d_gene, 74: j_gene, 75: cdr1_seq, 76: cdr2_seq, 77: ref_name, 78: ref_synonyms, 79: chain1_nt_acc, 80: chain1_nt_seq, 81: chain1_pro_acc, 82: chain1_pro_seq, 83: chain2_nt_acc, 84: chain2_nt_seq, 85: chain2_pro_acc, 86: chain2_pro_seq, 87: region, 88: mol1_modified_seq, 89: mol1_modification, 90: linear_peptide_modified_seq, 91: linear_peptide_modification, 92: disc_region, 93: e_location, 94: e_comments, 95: e_ev, 96: e_ref_region) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv("../../data/raw-data/IEDB/IEDB.csv", sep = ";", header = 0)

(273436, 214)
Unificate species
Check mhc names

100%|██████████| 273436/273436 [00:15<00:00, 17232.77it/s]
100%|██████████| 273436/273436 [00:14<00:00, 18897.25it/s]

{'H2-IEk alpha', 'H2-IAb alpha', 'H2-IAu alpha', 'H2-IAk alpha', 'Mamu-A1*065:01', 'H2-IEd alpha', 'H2-IAg7 alpha', 'H2-IAd alpha', 'Gaga-BF2*015:01', 'HLA-DPA', 'H2-IAq alpha', nan}
{'H2-IAu beta', 'H2-IEk beta', 'H2-IAd beta', 'H2-IEd beta', 'H2-IAb beta', 'H2-IAg7 beta', 'H2-IAq beta', 'H2-IAk beta', nan}

In [18]:
isinstance(mhcgnomes.parse('H2-IEk').alpha, mhcgnomes.allele.Allele)

True

In [33]:
mhcgnomes.parse('HLA-E*01:03').is_class1

True

In [34]:
mhcgnomes.parse('HLA-E*01:03').is_class2

False

In [40]:
iedb_clean = pd.read_csv("../../data/clean-data/IEDB_clean.csv", sep=";")
cedar_clean = pd.read_csv("../../data/clean-data/CEDAR_clean.csv", sep=";")
total_iedb = pd.concat([iedb_clean,cedar_clean], ignore_index=True).drop_duplicates(subset=["cdr3_alpha","cdr3_beta","epitope","mhc_alpha","mhc_beta"])
total_iedb.shape

(97751, 17)

In [ ]:
subset=["cdr3_alpha","cdr3_beta","epitope","mhc_alpha","mhc_beta"]

In [41]:
total_iedb['database'].value_counts()

database
IEDB    97751
Name: count, dtype: int64

In [42]:
cedar_clean

,id,D_alpha,D_beta,J_alpha,J_beta,V_alpha,V_beta,cdr3_alpha,cdr3_beta,epitope,mhc_alpha,mhc_beta,mhc_class,host_species,epitope_species,epitope_source,database
0,000060b0-ec9b-4edc-b287-a3847eb1a6bc,NaN,TRBD2*02,NaN,TRBJ2-1*01,NaN,TRBV6,NaN,ASRVRGWGIVNNEQF,GLCTLVAML,HLA-A*02:01,B2M,I,human,human gammaherpesvirus 4,YP_401660.1,CEDAR
1,00008466-49e5-43ae-b853-8d9e7133b52e,NaN,NaN,TRAJ35,NaN,TRAV12-1,NaN,VVNIGVGNVLH,NaN,LLFGYPVYV,HLA-A*24:02,B2M,I,human,Human T-cell leukemia virus type I,AYN25353.1,CEDAR
2,0001003d-3b6a-4815-9426-30aef4489600,NaN,NaN,TRAJ15,NaN,TRAV1-1,NaN,AVREAVETRQELLMI,NaN,YVLDHLIVV,HLA-A*02:01,B2M,I,human,human gammaherpesvirus 4,ABB89247.1,CEDAR
3,00015741-77e8-4f15-83ac-1e68e9465e4b,NaN,NaN,TRAJ13*01,TRBJ2-1*01,TRAV6D-3*01,TRBV13-3*01,AMSNSGTYQR,ASGGNYAEQF,SSPPMFRV,H2-K*b,B2M,I,mouse,Murid betaherpesvirus 1,CCE56713.1,CEDAR
4,00015741-77e8-4f15-83ac-1e68e9465e4b,NaN,NaN,TRAJ13*01,TRBJ2-1*01,TRAV6D-3*01,TRBV13-3*01,AMSNSGTYQR,ASGGNYAEQF,SSPPMFRV,H2-K*b,B2M,I,mouse,Murid betaherpesvirus 1,CCE56713.1,CEDAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128092,fff971a2-0240-460d-9b50-550838607c52,NaN,NaN,NaN,NaN,NaN,NaN,AVNGAGTALI,ASSISLGTAYEQY,KLGGALQAK,HLA-A*03:01,B2M,I,human,Human betaherpesvirus 5,AAR31448.1,CEDAR
128093,fffa56a7-040c-4693-922e-f89b3895a74b,NaN,NaN,NaN,NaN,NaN,NaN,AMREGLRGAQKLV,ASSRLPGPIQY,KLGGALQAK,HLA-A*03:01,B2M,I,human,Human betaherpesvirus 5,AAR31448.1,CEDAR
128094,fffa56a7-040c-4693-922e-f89b3895a74b,NaN,NaN,NaN,NaN,NaN,NaN,AMREGLRGAQKLV,ASSRLPGPIQY,KLGGALQAK,HLA-A*03:01,B2M,I,human,Human betaherpesvirus 5,AAR31448.1,CEDAR
128095,fffccb3b-3bd8-429b-a054-0f5450c9137e,NaN,NaN,TRAJ33,NaN,TRAV38-2/DV8,NaN,ALMDSNYQLI,NaN,RVRAYTYSK,HLA-A*03:01,B2M,I,human,human gammaherpesvirus 4,Q3KSS7.1,CEDAR
128096,fffd06ce-28ee-410d-9877-488fc88b4bf0,NaN,TRBD2,NaN,TRBJ2-7*01,NaN,TRBV4-3*01,NaN,SVDGTSSYEQY,GLCTLVAML,HLA-A*02:01,B2M,I,human,human gammaherpesvirus 4,YP_401660.1,CEDAR