In [2]:
import pandas as pd
from glob import glob

In [3]:
charged_samplesheet = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/results/charged/output_samplesheet.csv")
charged_samplesheet.head()

,train_file,test_file,model_type,mna_level,ngram_level,class_limit,iap_limit,sdf_train,train_id,test_id
0,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,3,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,5c2f3309493725ecea5c0f318d3c015c,NO_TEST
1,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,4,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,d7f616b6ffb61cbf06fe46e752b57e28,NO_TEST
2,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,5,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,c4817eab89e2be982cfcdae56af7d70d,NO_TEST
3,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,6,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,773315be5594eecb55e31584c2229aeb,NO_TEST
4,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,7,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,c29c8d5bb62ae7bd68db4e5e7daed629,NO_TEST

In [5]:
charged_logs = glob("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/results/charged/train_results/*.csv")
len(charged_logs)

39

In [7]:
charged_logs = glob("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/results/charged/models/*/*.HST")
len(charged_logs)

79

In [4]:
neutral_samplesheet = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/results/charged/output_samplesheet.csv")
neutral_samplesheet.head()

,train_file,test_file,model_type,mna_level,ngram_level,class_limit,iap_limit,sdf_train,train_id,test_id
0,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,3,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,5c2f3309493725ecea5c0f318d3c015c,NO_TEST
1,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,4,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,d7f616b6ffb61cbf06fe46e752b57e28,NO_TEST
2,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,5,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,c4817eab89e2be982cfcdae56af7d70d,NO_TEST
3,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,6,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,773315be5594eecb55e31584c2229aeb,NO_TEST
4,/projects/rat_gravitation/anton_disser/TCR-Pre...,/projects/rat_gravitation/anton_disser/TCR-Pre...,mna,7,1,3,0.7,/projects/rat_gravitation/anton_disser/pass-ne...,c29c8d5bb62ae7bd68db4e5e7daed629,NO_TEST