In [1]:
import pandas as pd
import mhcgnomes

## CDR3a_MHC

In [2]:
cdr3a_mhc = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/old/CDR3a_MHC.csv", sep = ";")
cdr3a_mhc.head()

,TCR_chain,CDR3_TCR_sequence,Epitope,host_species,class,MHC_allele,accession,database_access,protein_name,source_species,Source,good_mhc,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,alpha,AMSLYYGGSQGNLI,KIFGSLAFL,Human,I,HLA-A*02:01,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB,True,NaN,NaN,NaN
1,alpha,AMSLYYGGSQGNLI,KIFGSLAFL,Human,I,HLA-A*02:01,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB,True,NaN,NaN,NaN
2,alpha,AVSVEETSGSRLT,GILGFVFTL,Human,I,HLA-A*02:01,P03485.1,GenPept,Matrix protein 1,Influenza A virus (A/Puerto Rico/8/1934(H1N1))...,IEDB,True,NaN,NaN,NaN
3,alpha,ALSEAGTGGSYIPT,GILGFVFTL,Human,I,HLA-A*02:01,P03485.1,GenPept,Matrix protein 1,Influenza A virus (A/Puerto Rico/8/1934(H1N1))...,IEDB,True,NaN,NaN,NaN
4,alpha,AVIDYKLS,YLYDRLLRI,Human,I,HLA-A*02:01,Q14691.1,GenPept,DNA replication complex GINS protein PSF1,Homo sapiens (human),IEDB,True,NaN,NaN,NaN

In [3]:
cdr3a_mhc.query("host_species == 'Human'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3alpha_mhc_human.csv", sep =";")
cdr3a_mhc.query("host_species == 'Mouse'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3alpha_mhc_mouse.csv", sep =";")

## CDR3b_MHC

In [4]:
cdr3b_mhc = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/old/CDR3b_MHC.csv", sep = ";")
cdr3b_mhc.head()

/scratch/ipykernel_1615770/1716130328.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  cdr3b_mhc = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/old/CDR3b_MHC.csv", sep = ";")

,TCR_chain,CDR3_TCR_sequence,Epitope,host_species,class,MHC_allele,accession,database_access,protein_name,source_species,Source,good_mhc,Unnamed: 12,Unnamed: 13
0,beta,ASSLEIFGGIADTDTQY,KIFGSLAFL,Human,I,HLA-A*02:01,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB,True,NaN,NaN
1,beta,ASSLEIFGGIADTDTQY,KIFGSLAFL,Human,I,HLA-A*02:01,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB,True,NaN,NaN
2,beta,ASSIRSSYEQY,GILGFVFTL,Human,I,HLA-A*02:01,P03485.1,GenPept,Matrix protein 1,Influenza A virus (A/Puerto Rico/8/1934(H1N1))...,IEDB,True,NaN,NaN
3,beta,ASSFFHNNEQF,GILGFVFTL,Human,I,HLA-A*02:01,P03485.1,GenPept,Matrix protein 1,Influenza A virus (A/Puerto Rico/8/1934(H1N1))...,IEDB,True,NaN,NaN
4,beta,ASSMFVGQPQH,GILGFVFTL,Human,I,HLA-A*02:01,P03485.1,GenPept,Matrix protein 1,Influenza A virus (A/Puerto Rico/8/1934(H1N1))...,IEDB,True,NaN,NaN

In [5]:
cdr3b_mhc.query("host_species == 'Human'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3beta_mhc_human.csv", sep =";")
cdr3b_mhc.query("host_species == 'Mouse'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3beta_mhc_mouse.csv", sep =";")

## CDR3a_epitope

In [6]:
cdr3a_epi = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/old/CDR3a_epitope.csv", sep = ";")
cdr3a_epi.head()

,TCR_chain,CDR3_TCR_sequence,host_species,Epitope,accession,database_access,protein_name,source_species,Source
0,alpha,AMSLYYGGSQGNLI,Human,KIFGSLAFL,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB
1,alpha,AMSLYYGGSQGNLI,Human,KIFGSLAFL,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB
2,alpha,ATVLRMDSSYKLI,Human,TPRVTGGGAM,YP_002608275.1,GenPept,tegument protein pp65,Human herpesvirus 5 (Human cytomegalovirus),IEDB
3,alpha,AYRSARDSSYKLI,Human,TPRVTGGGAM,YP_002608275.1,GenPept,tegument protein pp65,Human herpesvirus 5 (Human cytomegalovirus),IEDB
4,alpha,AVSVEETSGSRLT,Human,GILGFVFTL,P03485.1,GenPept,Matrix protein 1,Influenza A virus (A/Puerto Rico/8/1934(H1N1))...,IEDB

In [7]:
cdr3a_epi.query("host_species == 'Human'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3alpha_epitope_human.csv", sep =";")
cdr3a_epi.query("host_species == 'Mouse'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3alpha_epitope_mouse.csv", sep =";")

## CDR3b_epitope

In [8]:
cdr3b_epi = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/old/CDR3b_epitope.csv", sep = ";")
cdr3b_epi.head()

/scratch/ipykernel_1615770/3922694492.py:1: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  cdr3b_epi = pd.read_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/old/CDR3b_epitope.csv", sep = ";")

,TCR_chain,CDR3_TCR_sequence,host_species,Epitope,accession,database_access,protein_name,source_species,Source,Unnamed: 9,Unnamed: 10
0,beta,ASSLEIFGGIADTDTQY,Human,KIFGSLAFL,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB,NaN,NaN
1,beta,ASSLEIFGGIADTDTQY,Human,KIFGSLAFL,AAA75493.1,GenPept,HER2 receptor,Homo sapiens (human),IEDB,NaN,NaN
2,beta,ASSLIGVSSYNEQF,Human,TPRVTGGGAM,YP_002608275.1,GenPept,tegument protein pp65,Human herpesvirus 5 (Human cytomegalovirus),IEDB,NaN,NaN
3,beta,ASSDHSVTGISSPLH,Human,TPRVTGGGAM,YP_002608275.1,GenPept,tegument protein pp65,Human herpesvirus 5 (Human cytomegalovirus),IEDB,NaN,NaN
4,beta,ASSPGGGKETQY,Human,DEEDAIAAY,AAR31419.1,GenPept,UL123,NaN,NaN,NaN,NaN

In [9]:
cdr3b_epi.query("host_species == 'Human'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3beta_epitope_human.csv", sep =";")
cdr3b_epi.query("host_species == 'Mouse'").to_csv("/projects/rat_gravitation/anton_disser/TCR-Pred/03_26/data/v2023/cdr3beta_epitope_mouse.csv", sep =";")