In [2]:
import os
import sys
import pandas as pd
from getpass import getpass

In [63]:
sys.path.append('../../../data_prepare')

In [98]:
import importlib
import database
import IEDB
importlib.reload(IEDB)
importlib.reload(database)

In [99]:
iedb = IEDB.IEDB("81.177.141.179","iedb_svc",getpass(), database = "IEDB")

 ·········

In [45]:
raw_data = iedb.acquire()
raw_data.head()

tcell

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):
/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:87: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tbl = pd.concat([tbl, chunk], ignore_index = False)

curated_epitope

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):
/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:87: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tbl = pd.concat([tbl, chunk], ignore_index = False)

object

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):
/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:87: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  tbl = pd.concat([tbl, chunk], ignore_index = False)

epitope_object

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):

epitope

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):

tcell_receptor

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):

curated_receptor

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):

distinct_receptor

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):

distinct_chain

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):

mhc_allele_restriction

/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  for chunk in pd.read_sql(f"SELECT * FROM {name};", con = connection, chunksize = chunk_size):
/home/asmirnov/dissertation_new/TCRpred/notebooks/tests/data_prepare/../../../data_prepare/IEDB.py:89: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables["organism_names"] = pd.read_sql("SELECT organism_id, name_txt FROM organism_names WHERE name_class = 'scientific name';", con = connection)

Merging...Can take a long time
TCR information...
Epitope information...
MHC information...
Merging...
Finished

,tcell_id,reference_id,curated_epitope_id,as_location,as_type_id,as_char_value,as_num_value,as_inequality,as_num_subjects,as_num_responded,...,e_comments,e_object_id,related_object_id,related_object_type,e_ev,e_ref_start,e_ref_end,e_ref_region,epitope_source,Database
0,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,None,NaN,NaN,...,None,307021.0,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB
1,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,None,NaN,NaN,...,None,307021.0,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB
2,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,None,NaN,NaN,...,None,307021.0,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB
3,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,None,NaN,NaN,...,None,307021.0,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB
4,2105208.0,1027859.0,1501956.0,"Figures 2, 3, 4, Table I, Supplemental Tables ...",174.0,Positive,2.990,=,NaN,NaN,...,None,1263560.0,NaN,None,Representative selection,NaN,NaN,None,Human immunodeficiency virus 1,IEDB

In [46]:
iedb.save(raw_data,"../../../data/raw_IEDB.csv")

In [47]:
raw_data.shape

(273500, 214)

In [48]:
iedb.get_latest_update_date()

(datetime.datetime(2026, 1, 25, 0, 0), datetime.datetime(2026, 1, 18, 0, 0))

In [100]:
tcr_epi_non_filt, tcr_epi_filt = iedb.clean(raw_data,"tcr-epitope")

ValueError: cannot set a frame with no defined index and a scalar

In [101]:
tcr_epi_non_filt.shape

(0, 234)

In [102]:
tcr_epi_filt.shape

(18, 11)

In [80]:
tcr_epi_filt

,ReceptorID,Database,Chain,Species,Structure,Activity,EpitopeProtein,EpitopeOrganism,V,D,J
has_reference,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ab_receptor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ab_chains,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
included_species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_cdr3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
valid_cdr3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_epitope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_epitope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
valid_epitope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
no_modif_epitope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_included_host,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_complete_mhc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
without_mutations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
canonical_mhc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
not_b2m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
success_parse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
# Source - https://stackoverflow.com/a/34325723
# Posted by Greenstick, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-03, License - CC BY-SA 4.0

# Print iterations progress
def printProgressBar (iteration, total, prefix = '', suffix = '', decimals = 1, length = 100, fill = '█', printEnd = "\r"):
    """
    Call in a loop to create terminal progress bar
    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
        printEnd    - Optional  : end character (e.g. "\r", "\r\n") (Str)
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end = printEnd)
    # Print New Line on Complete
    if iteration == total: 
        print()

In [171]:
import uuid
import mhcgnomes
import pandas as pd
from tools import get_mhc_class

class DatabaseTest():

    def __init__(self, database = None):
        super().__init__()
        self._tcr_epitope_schema = {}
        self._tcr_mhc_schema = {}
        self._database = database
        self._filter_rules = {}
        self._seq_pattern = f"^[ACDEFGHIKLMNPQRSTVWY]+$" # Use in queries
        self._included_species = ['human','mouse'] # Use in queries
        self._species_cols = []
        self._species_names = {
            "Homo sapiens":"human",
            "Mus musculus":"mouse"
        }
        self._receptor_col = ""
        self._mhc_cols = []
        self._mhc_class_col = "MHCclass"
        self._mhc_fix_col = "MHCchain"
        self._dup_cols = []

    def acquire(self):
        raise NotImplementedError("Should be used certain acquiring for the database")
    
    def clean(self, raw_data: pd.DataFrame, dataset: str):
        assert dataset == "tcr-epitope" or dataset == "tcr-mhc", f"Incorrect dataset {dataset}"
        for k in self._tcr_epitope_schema.keys():
            if k != self._mhc_fix_col: # _mhc_fix_col introduced only in cleaning
                assert k in raw_data.columns, f"Incorrect column names {k}. The raw data has been downloaded using Database.acquire method?"
        data_with_filters = self._preprocess(raw_data)
        dedup_data = data_with_filters.drop_duplicates(subset=self._dup_cols, ignore_index=True)
        
        return (
            dedup_data,
            self._apply_filters(dedup_data, dataset)
        )
    
    
    def preprocess(self, data:pd.DataFrame) -> pd.DataFrame:
        fixed_species_names = self.fix_species(data, self._species_cols, self._species_names)
        fixed_receptor_id = self.calculate_receptor_id(fixed_species_names, self._receptor_col)
        mhc_reshaped = pd.melt(fixed_receptor_id, 
                              id_vars = fixed_receptor_id.columns[~fixed_receptor_id.columns.isin(self._mhc_cols)],               
                              value_vars = self._mhc_cols,
                              var_name = "mhc_chain_type",
                              value_name = self._mhc_fix_col,
                              ignore_index = True)
        fixed_mhc_allele = self._fix_mhc_allele(mhc_reshaped)
        calculated_filters = self._calculate_filters(fixed_mhc_allele)
        return calculated_filters

    
    def get_latest_update_date(self):
        raise NotImplementedError("Should be used certain cleaner for the database")
    

    def fix_mhc_allele(self, data: pd.DataFrame) -> pd.DataFrame:
        fixed_data = data.copy(deep=True)
        fixed_data["success_parse"] = False
        total = len(fixed_data.index)
        for k,i in enumerate(fixed_data.index):
            printProgressBar(k,total)
            allele=None
            try:
                allele = mhcgnomes.parse(fixed_data.loc[i, self._mhc_fix_col])
            except Exception:
                fixed_data.loc[i, "success_parse"] = False
            else:
                if type(allele) is mhcgnomes.allele.Allele:
                    if allele.gene.species.name == "Homo sapiens":
                        if len(allele.allele_fields) < 2:
                            fixed_data.loc[i, "success_parse"] = False
                        elif len(allele.allele_fields) == 2:
                            fixed_data.loc[i, self._mhc_fix_col] = allele.to_string()
                            fixed_data.loc[i,  self._mhc_class_col] = get_mhc_class(fixed_data.loc[i, self._mhc_fix_col])
                            fixed_data.loc[i, "success_parse"] = True
                        else:
                            fixed_data.loc[i, self._mhc_fix_col] = allele.restrict_allele_fields(2, drop_annotations=True, drop_mutations=True).to_string()
                            fixed_data.loc[i,  self._mhc_class_col] = get_mhc_class(fixed_data.loc[i, self._mhc_fix_col])
                            fixed_data.loc[i, "success_parse"] = True
                    elif allele.gene.species.name == "Mus musculus":
                        fixed_data.loc[i, self._mhc_fix_col] = allele.to_string()
                        fixed_data.loc[i,  self._mhc_class_col] = get_mhc_class(fixed_data.loc[i, self._mhc_fix_col])
                        fixed_data.loc[i, "success_parse"] = True
                    else:
                        fixed_data.loc[i, "success_parse"] = False
                else:
                    fixed_data.loc[i, "success_parse"] = False

        self._filter_rules["success_parse"] = "success_parse == True"
        return fixed_data
        

    def allele_to_compact_name(self, allele: str) -> str:
        return mhcgnomes.parse(allele).to_string()
    
    def save(self, data: pd.DataFrame, output: str) -> None:
        data.to_csv(output,sep = ";",index = False)

    def fix_species(self, data: pd.DataFrame, columns: list[str], values: dict[str,str]) -> pd.DataFrame:
        cleaned_data = data.copy(deep=True)
        for col in columns:
            for k, v in values.items():
                assert v in self._included_species, f"{v} doesn`t include"
                cleaned_data.loc[cleaned_data[col].str.contains(k),col] = v
        return cleaned_data

    def calculate_filters(self, data: pd.DataFrame) -> pd.DataFrame:
        cleaned_data = data.copy(deep=True)
        for f, e in self._filter_rules.items():
            cleaned_data[f] = cleaned_data.eval(e)
        return cleaned_data
    
    def calculate_receptor_id(self, data: pd.DataFrame, column: str) -> pd.DataFrame:
        cleaned_data = data.copy(deep=True)
        unique_id = cleaned_data[column].unique()
        replacement = {k:str(uuid.uuid4()) for k in unique_id}
        cleaned_data[column] = cleaned_data[column].map(replacement)
        return cleaned_data
    
    def apply_filters(self, data:pd.DataFrame, dataset: str) -> pd.DataFrame:
        final_columns = self._tcr_epitope_schema if dataset == "tcr-epitope" else self._tcr_mhc_schema
        cleaned_data = data.copy(deep=True)
        filter_names = list(self._filter_rules.keys())
        cleaned_data["PASSED"] = cleaned_data.loc[:,filter_names].all()
        selected_columns = list(final_columns.keys())
        return cleaned_data.query("PASSED").loc[:,selected_columns].rename(columns = final_columns)

In [172]:
database = DatabaseTest()

In [147]:
fixed_species_names = database.fix_species(raw_data, ["species_name_receptor","species_name_chain","mhc_source","host_organism"], {"Homo sapiens":"human","Mus musculus":"mouse"})
fixed_species_names["species_name_receptor"].value_counts()

species_name_receptor
human                  260218
mouse                   12280
synthetic construct       994
Macaca mulatta              6
Gallus gallus               2
Name: count, dtype: int64

In [148]:
fixed_receptor_id = database.calculate_receptor_id(fixed_species_names, "curated_receptor_id")
fixed_receptor_id["curated_receptor_id"].head()

0    121418d8-0c9b-4c2e-9a9a-bd991e0250bd
1    121418d8-0c9b-4c2e-9a9a-bd991e0250bd
2    121418d8-0c9b-4c2e-9a9a-bd991e0250bd
3    121418d8-0c9b-4c2e-9a9a-bd991e0250bd
4    2043f9dc-edff-45ba-9c58-52e4bae31aef
Name: curated_receptor_id, dtype: object

In [149]:
mhc_reshaped = pd.melt(fixed_receptor_id, 
                       id_vars = fixed_receptor_id.columns[~fixed_receptor_id.columns.isin(["chain_i_name","chain_ii_name"])],               
                       value_vars = ["chain_i_name","chain_ii_name"],
                       var_name = "mhc_chain_type",
                       value_name = "MHCchain",
                       ignore_index = True)
mhc_reshaped.head()

,tcell_id,reference_id,curated_epitope_id,as_location,as_type_id,as_char_value,as_num_value,as_inequality,as_num_subjects,as_num_responded,...,related_object_id,related_object_type,e_ev,e_ref_start,e_ref_end,e_ref_region,epitope_source,Database,mhc_chain_type,MHCchain
0,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,None,NaN,NaN,...,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01
1,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,None,NaN,NaN,...,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01
2,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,None,NaN,NaN,...,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01
3,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,None,NaN,NaN,...,NaN,None,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01
4,2105208.0,1027859.0,1501956.0,"Figures 2, 3, 4, Table I, Supplemental Tables ...",174.0,Positive,2.990,=,NaN,NaN,...,NaN,None,Representative selection,NaN,NaN,None,Human immunodeficiency virus 1,IEDB,chain_i_name,HLA-B*51:01

In [173]:
fixed_mhc_allele = database.fix_mhc_allele(mhc_reshaped)
fixed_mhc_allele.head()

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

,tcell_id,reference_id,curated_epitope_id,as_location,as_type_id,as_char_value,as_num_value,as_inequality,as_num_subjects,as_num_responded,...,e_ev,e_ref_start,e_ref_end,e_ref_region,epitope_source,Database,mhc_chain_type,MHCchain,success_parse,MHCclass
0,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,None,NaN,NaN,...,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01,True,I
1,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,None,NaN,NaN,...,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01,True,I
2,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,None,NaN,NaN,...,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01,True,I
3,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,None,NaN,NaN,...,Representative selection,NaN,NaN,None,Human T-cell leukemia virus type I,IEDB,chain_i_name,HLA-A*02:01,True,I
4,2105208.0,1027859.0,1501956.0,"Figures 2, 3, 4, Table I, Supplemental Tables ...",174.0,Positive,2.990,=,NaN,NaN,...,Representative selection,NaN,NaN,None,Human immunodeficiency virus 1,IEDB,chain_i_name,HLA-B*51:01,True,I

In [159]:
allele = mhcgnomes.parse(mhc_reshaped.loc[0, "MHCchain"])
allele

Allele(gene=Gene(species=Species(name='Homo sapiens', mhc_prefix='HLA'), name='A', mutations=()), allele_fields=('02', '01'), annotations=(), mutations=())

In [160]:
len(allele.allele_fields) < 2

False

In [162]:
len(allele.allele_fields)

2

In [163]:
allele.gene.species

Species(name='Homo sapiens', mhc_prefix='HLA')

In [165]:
allele.gene.species.name == "Homo sapiens"

True

In [170]:
type(allele) is mhcgnomes.allele.Allele

True

In [174]:
fixed_mhc_allele["success_parse"].value_counts()

success_parse
False    362548
True     184452
Name: count, dtype: int64

In [175]:
fixed_mhc_allele.loc[~fixed_mhc_allele["success_parse"],"MHCchain"].head()

1095    HLA-DQA
1096    HLA-DQA
1097    HLA-DQA
1098    HLA-DQA
1099    HLA-DQA
Name: MHCchain, dtype: object

In [176]:
fixed_mhc_allele.loc[~fixed_mhc_allele["success_parse"],"MHCchain"].tail()

546995    H2-IAb beta
546996    H2-IAb beta
546997    H2-IAb beta
546998    H2-IAb beta
546999    H2-IAb beta
Name: MHCchain, dtype: object

In [177]:
fixed_mhc_allele.loc[fixed_mhc_allele["success_parse"],"MHCchain"].tail()

546796    HLA-DPB1*04:01
546797    HLA-DRB5*01:01
546798    HLA-DRB5*01:01
546799    HLA-DRB5*01:02
546800    HLA-DRB5*01:02
Name: MHCchain, dtype: object

In [179]:
fixed_mhc_allele.loc[fixed_mhc_allele["success_parse"],"host_organism"].value_counts()

host_organism
human    174119
mouse     10333
Name: count, dtype: int64

In [180]:
fixed_mhc_allele.loc[fixed_mhc_allele["success_parse"],"MHCclass"].value_counts()

MHCclass
I     168671
II     15781
Name: count, dtype: int64

In [181]:
fixed_mhc_allele.loc[fixed_mhc_allele["success_parse"] & fixed_mhc_allele["host_organism"] == "mouse","MHCclass"].value_counts()

Series([], Name: count, dtype: int64)

In [183]:
mhcgnomes.parse("H2-IAb")

Pair(alpha=Allele(gene=Gene(species=Species(name='Mus musculus', mhc_prefix='H2'), name='AA', mutations=()), allele_fields=('b',), annotations=(), mutations=()), beta=Allele(gene=Gene(species=Species(name='Mus musculus', mhc_prefix='H2'), name='AB', mutations=()), allele_fields=('b',), annotations=(), mutations=()), mhc_class='II')

In [184]:
mhcgnomes.parse("H2-IAa")

Pair(alpha=Allele(gene=Gene(species=Species(name='Mus musculus', mhc_prefix='H2'), name='AA', mutations=()), allele_fields=('k',), annotations=(), mutations=()), beta=Allele(gene=Gene(species=Species(name='Mus musculus', mhc_prefix='H2'), name='AB', mutations=()), allele_fields=('k',), annotations=(), mutations=()), mhc_class='II')

In [185]:
mhcgnomes.parse("H2-IAb").to_string()

'H2-AA*b/AB*b'

TODO: стоит ли разбивать пары второго класса на цепи или оставить объединенными.

In [190]:
allele_b = mhcgnomes.Allele(mhcgnomes.parse("B2M"),allele_fields=())
allele_a = mhcgnomes.parse("HLA-A:02:01")
pair= mhcgnomes.Pair(allele_a,allele_b, mhc_class = "I")
pair

Pair(alpha=Allele(gene=Gene(species=Species(name='Homo sapiens', mhc_prefix='HLA'), name='A', mutations=()), allele_fields=('02', '01'), annotations=(), mutations=()), beta=Allele(gene=Gene(species=Species(name='Homo sapiens', mhc_prefix='HLA'), name='B2M', mutations=()), allele_fields=(), annotations=(), mutations=()), mhc_class='I')

In [191]:
mhcgnomes.parse("HLA-DRB*01:01")

Allele(gene=Gene(species=Species(name='Homo sapiens', mhc_prefix='HLA'), name='DRB1', mutations=()), allele_fields=('01', '01'), annotations=(), mutations=())

Так ли уж нужен классификатор cdr3-mhc и  какие есть пары.

In [4]:
raw_data = pd.read_csv("../../../data/raw_IEDB.csv", sep = ';')
raw_data.head()

/scratch/ipykernel_908085/1108324106.py:1: DtypeWarning: Columns (3,7,11,12,14,15,16,17,18,19,20,22,23,24,26,27,28,30,32,33,34,35,37,38,39,41,43,44,45,46,47,49,51,52,53,54,56,57,58,60,62,64,65,67,68,69,70,71,72,73,74,81,82,83,84,86,87,88,90,99,100,105,106,108,109,110,112,118,119,120,121,131,132,133,134,141,142,145,146,152,153,154,155,158,159,160,161,170,178,179,188,189,192,202,204,208,211) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv("../../../data/raw_IEDB.csv", sep = ';')

,tcell_id,reference_id,curated_epitope_id,as_location,as_type_id,as_char_value,as_num_value,as_inequality,as_num_subjects,as_num_responded,...,e_comments,e_object_id,related_object_id,related_object_type,e_ev,e_ref_start,e_ref_end,e_ref_region,epitope_source,Database
0,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,NaN,NaN,NaN,...,NaN,307021.0,NaN,NaN,Representative selection,NaN,NaN,NaN,Human T-cell leukemia virus type I,IEDB
1,3467299.0,1008123.0,1199832.0,Figure 2,582.0,Positive,110000.000,NaN,NaN,NaN,...,NaN,307021.0,NaN,NaN,Representative selection,NaN,NaN,NaN,Human T-cell leukemia virus type I,IEDB
2,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,NaN,NaN,NaN,...,NaN,307021.0,NaN,NaN,Representative selection,NaN,NaN,NaN,Human T-cell leukemia virus type I,IEDB
3,3467300.0,1008123.0,1199832.0,Figure 2,583.0,Positive,0.093,NaN,NaN,NaN,...,NaN,307021.0,NaN,NaN,Representative selection,NaN,NaN,NaN,Human T-cell leukemia virus type I,IEDB
4,2105208.0,1027859.0,1501956.0,"Figures 2, 3, 4, Table I, Supplemental Tables ...",174.0,Positive,2.990,=,NaN,NaN,...,NaN,1263560.0,NaN,NaN,Representative selection,NaN,NaN,NaN,Human immunodeficiency virus 1,IEDB

In [ ]:
def fix_values(data: pd.DataFrame, columns: list, rules: dict[str,str]) -> pd.DataFrame:
    cleaned_data = data.copy(deep=True)
    for col in columns:
        cleaned_data[col] = cleaned_data[col].map(rules)
    return cleaned_data

def calculate_receptor_id(self, data: pd.DataFrame, column: str) -> pd.DataFrame:
    cleaned_data = data.copy(deep=True)
    unique_id = cleaned_data[column].unique()
    replacement = {k:str(uuid.uuid4()) for k in unique_id}
    cleaned_data[column] = cleaned_data[column].map(replacement)
    return cleaned_data

def fix_mhc_allele(self, data: pd.DataFrame) -> pd.DataFrame:
    fixed_data = data.copy(deep=True)
    fixed_data["success_parse"] = False
    total = len(fixed_data.index)
    for k,i in enumerate(fixed_data.index):
        printProgressBar(k,total)
        allele=None
        try:
            allele = mhcgnomes.parse(fixed_data.loc[i, self._mhc_fix_col])
        except Exception:
            fixed_data.loc[i, "success_parse"] = False
        else:
            if type(allele) is mhcgnomes.allele.Allele:
                if allele.gene.species.name == "Homo sapiens":
                    if len(allele.allele_fields) < 2:
                        fixed_data.loc[i, "success_parse"] = False
                    elif len(allele.allele_fields) == 2:
                        fixed_data.loc[i, self._mhc_fix_col] = allele.to_string()
                        fixed_data.loc[i,  self._mhc_class_col] = get_mhc_class(fixed_data.loc[i, self._mhc_fix_col])
                        fixed_data.loc[i, "success_parse"] = True
                    else:
                        fixed_data.loc[i, self._mhc_fix_col] = allele.restrict_allele_fields(2, drop_annotations=True, drop_mutations=True).to_string()
                        fixed_data.loc[i,  self._mhc_class_col] = get_mhc_class(fixed_data.loc[i, self._mhc_fix_col])
                        fixed_data.loc[i, "success_parse"] = True
                elif allele.gene.species.name == "Mus musculus":
                    fixed_data.loc[i, self._mhc_fix_col] = allele.to_string()
                    fixed_data.loc[i,  self._mhc_class_col] = get_mhc_class(fixed_data.loc[i, self._mhc_fix_col])
                    fixed_data.loc[i, "success_parse"] = True
                else:
                    fixed_data.loc[i, "success_parse"] = False
            else:
                fixed_data.loc[i, "success_parse"] = False

    self._filter_rules["success_parse"] = "success_parse == True"
    return fixed_data